version: "3.7"
services:
  api:
    build: .
    expose:
      - 8000:8000
    env_file: .env
    volumes:
      - .:/app
      - .:/data
    command: uvicorn api:app --host 0.0.0.0 --port 8000 --reload

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/usr/share/nginx/html
    ports:
      - 8000:80

